### ISSUE TITLE
Improve performance for `dashboard.organizations`

### ISSUE THREAD

**Issue by leomao10** [maestrano/mno-enterprise#73]
Hey there, 

I recently run into this code and I think it can create performance issue for dashboard request:
https://github.com/maestrano/mno-enterprise/blob/master/core/app/models/mno_enterprise/impac/dashboard.rb#L21

```
    def organizations
      self.organization_ids.map do |uid|
        MnoEnterprise::Organization.find_by(uid: uid)
      end
    end
```

Base on the code, it will call `MnoEnterprise::Organization.find_by(uid: uid)` for every `organization_id`, and since `MnoEnterprise::Organization.find_by` will call external services, it will slow down this method a lot when there are lots organization_ids.

I think we can change the `organizations` method to use `where` instead of `find_by`

**Comment by ouranos** [comment]
Fixed in v2.0.6
